-- PostgreSQL / Supabase schema derived from fitness_app.sql
-- Import this file into the Supabase SQL editor or a PostgreSQL client.

DROP TABLE IF EXISTS
  completion_requests,
  user_challenges,
  user_achievements,
  ai_validation_logs,
  hire_disputes,
  hire_sessions,
  post_announcements,
  trainer_reviews,
  trainer_hires,
  workout_plan_items,
  diet_plan_items,
  recipe_tags,
  ingredients,
  workout_plans,
  diet_plans,
  payments,
  notifications,
  chats,
  challenges,
  achievements,
  trainer_posts,
  exercises,
  recipes,
  users
CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'trainer', 'admin')),
  height NUMERIC(5, 2),
  weight NUMERIC(5, 2),
  goal TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  fcm_token VARCHAR(500),
  gender VARCHAR(10) CHECK (gender IN ('male', 'female')),
  dob DATE,
  avatar_url VARCHAR(500),
  profession VARCHAR(255),
  bio TEXT,
  experience_years INTEGER,
  certification VARCHAR(255),
  phone_number VARCHAR(20),
  certification_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (certification_status IN ('pending', 'approved', 'rejected')),
  certification_url VARCHAR(500),
  last_lat NUMERIC(10, 7),
  last_lon NUMERIC(10, 7),
  notification_prefs TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  deactivated_at TIMESTAMPTZ
);

CREATE TABLE achievements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  rule_type VARCHAR(30) NOT NULL CHECK (rule_type IN ('weekly_streak', 'steps_total', 'calories_total', 'distance_total', 'challenge_complete')),
  rule_value INTEGER NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  icon VARCHAR(100)
);

CREATE TABLE exercises (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50),
  muscle VARCHAR(255),
  equipment VARCHAR(255),
  difficulty VARCHAR(50),
  instructions TEXT,
  safety_info TEXT,
  youtube_url VARCHAR(500),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  image VARCHAR(500),
  calories NUMERIC(8, 2) DEFAULT 0,
  protein NUMERIC(8, 2) DEFAULT 0,
  fat NUMERIC(8, 2) DEFAULT 0,
  carbs NUMERIC(8, 2) DEFAULT 0,
  vegetarian BOOLEAN DEFAULT FALSE,
  vegan BOOLEAN DEFAULT FALSE,
  gluten_free BOOLEAN DEFAULT FALSE,
  ready_in_minutes INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  instructions TEXT
);

CREATE TABLE challenges (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK (type IN ('steps', 'calories', 'distance')),
  target_value INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  description TEXT,
  url VARCHAR(500),
  points INTEGER NOT NULL DEFAULT 10,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('pending', 'active', 'rejected')),
  validation_note TEXT,
  challenge_type VARCHAR(20) NOT NULL DEFAULT 'auto' CHECK (challenge_type IN ('auto', 'online', 'offline')),
  event_start_time TIME,
  event_end_time TIME,
  max_participants INTEGER,
  location VARCHAR(255)
);

CREATE TABLE workout_plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  generated_by VARCHAR(20) NOT NULL CHECK (generated_by IN ('ai', 'trainer')),
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'verified', 'modified', 'denied')),
  validation_note TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  survey_input TEXT,
  session_id INTEGER
);

CREATE TABLE diet_plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'verified', 'modified', 'denied')),
  validation_note TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  survey_input TEXT
);

CREATE TABLE trainer_posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  focus_areas VARCHAR(500),
  services TEXT,
  price INTEGER NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  session_type VARCHAR(20) NOT NULL DEFAULT 'online' CHECK (session_type IN ('online', 'offline')),
  location VARCHAR(255),
  visibility VARCHAR(20) NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  max_slots INTEGER,
  schedule TEXT,
  enrollment_deadline DATE,
  program_start_date DATE,
  deactivated_by VARCHAR(20) CHECK (deactivated_by IN ('system', 'trainer', 'admin'))
);

CREATE TABLE trainer_hires (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER NOT NULL REFERENCES trainer_posts(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(30) DEFAULT 'pending_payment' CHECK (status IN ('pending_payment', 'pending_approval', 'enrolled', 'active', 'ended', 'cancelled', 'expired')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  payment_order_id VARCHAR(255),
  trainer_response_deadline TIMESTAMPTZ,
  early_end_requested_by VARCHAR(20) CHECK (early_end_requested_by IN ('member', 'trainer')),
  early_end_requested_at TIMESTAMPTZ
);

CREATE TABLE hire_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hire_id INTEGER NOT NULL REFERENCES trainer_hires(id) ON DELETE CASCADE,
  scheduled_date DATE NOT NULL,
  scheduled_day VARCHAR(20) NOT NULL,
  scheduled_start VARCHAR(10) NOT NULL,
  confirm_code VARCHAR(6),
  code_expires_at TIMESTAMPTZ,
  trainer_started_at TIMESTAMPTZ,
  member_confirmed_at TIMESTAMPTZ,
  status VARCHAR(20) DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'started', 'confirmed', 'missed')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  trainer_note TEXT
);

CREATE TABLE hire_disputes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hire_id INTEGER NOT NULL REFERENCES trainer_hires(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason VARCHAR(30) NOT NULL CHECK (reason IN ('trainer_no_show', 'wrong_content', 'technical_issues', 'other')),
  description TEXT,
  status VARCHAR(20) DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'rejected')),
  admin_note TEXT,
  resolved_by INTEGER,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trainer_reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hire_id INTEGER NOT NULL UNIQUE REFERENCES trainer_hires(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER NOT NULL REFERENCES trainer_posts(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  sessions_total INTEGER DEFAULT 0,
  sessions_attended INTEGER DEFAULT 0
);

CREATE TABLE user_challenges (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  challenge_id INTEGER NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  current_value INTEGER DEFAULT 0,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'completed'))
);

CREATE TABLE completion_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_challenge_id INTEGER NOT NULL REFERENCES user_challenges(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  challenge_id INTEGER NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  proof_url VARCHAR(500),
  note TEXT,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by INTEGER,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_achievements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  achievement_id INTEGER NOT NULL REFERENCES achievements(id) ON DELETE CASCADE,
  earned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  steps INTEGER DEFAULT 0,
  calories INTEGER DEFAULT 0,
  distance NUMERIC(10, 2) DEFAULT 0,
  exercise_minutes INTEGER DEFAULT 0,
  sleep_hours NUMERIC(4, 1) DEFAULT 0,
  workout_completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE workout_plan_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_plan_id INTEGER NOT NULL REFERENCES workout_plans(id) ON DELETE CASCADE,
  exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  sets INTEGER,
  reps INTEGER,
  duration INTEGER,
  day VARCHAR(20),
  is_done BOOLEAN DEFAULT FALSE,
  week_start DATE
);

CREATE TABLE diet_plan_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diet_plan_id INTEGER NOT NULL REFERENCES diet_plans(id) ON DELETE CASCADE,
  day VARCHAR(20) NOT NULL,
  meal_type VARCHAR(20) NOT NULL,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE
);

CREATE TABLE ai_validation_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL,
  plan_type VARCHAR(20) NOT NULL CHECK (plan_type IN ('workout', 'diet')),
  admin_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(20) NOT NULL CHECK (action IN ('draft', 'verified', 'modified', 'denied')),
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id VARCHAR(255) NOT NULL UNIQUE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  status VARCHAR(30) DEFAULT 'pending' CHECK (status IN ('pending', 'settlement', 'failed', 'expired', 'refunded', 'partial_refund')),
  transaction_id VARCHAR(255),
  payment_type VARCHAR(50),
  snap_token TEXT,
  snap_redirect_url TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50) DEFAULT 'general',
  data TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_announcements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES trainer_posts(id) ON DELETE CASCADE,
  trainer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recipe_tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  tag VARCHAR(50) NOT NULL
);

CREATE TABLE ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  metric_value NUMERIC(10, 3),
  metric_unit VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_workout_user ON workout_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_workout_session ON workout_plans(session_id);
CREATE INDEX IF NOT EXISTS idx_diet_user ON diet_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_user_date ON activity_logs(user_id, date);
CREATE INDEX IF NOT EXISTS idx_user_challenges ON user_challenges(user_id, challenge_id);
CREATE INDEX IF NOT EXISTS idx_payment_user ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_chat_sender ON chats(sender_id);
CREATE INDEX IF NOT EXISTS idx_chat_receiver ON chats(receiver_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversation ON chats(sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS idx_trainer_posts_trainer ON trainer_posts(trainer_id);
CREATE INDEX IF NOT EXISTS idx_trainer_hires_member ON trainer_hires(member_id);
CREATE INDEX IF NOT EXISTS idx_trainer_hires_post ON trainer_hires(post_id);
CREATE INDEX IF NOT EXISTS idx_trainer_reviews_post ON trainer_reviews(post_id);
CREATE INDEX IF NOT EXISTS idx_recipe_tags ON recipe_tags(recipe_id, tag);
CREATE INDEX IF NOT EXISTS idx_ingredients_recipe ON ingredients(recipe_id);
CREATE INDEX IF NOT EXISTS idx_diet_plan_items ON diet_plan_items(diet_plan_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_post_announcements_post ON post_announcements(post_id);
CREATE INDEX IF NOT EXISTS idx_hire_sessions_hire ON hire_sessions(hire_id);
CREATE INDEX IF NOT EXISTS idx_hire_sessions_date ON hire_sessions(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_hire_disputes_hire ON hire_disputes(hire_id);
CREATE INDEX IF NOT EXISTS idx_hire_disputes_status ON hire_disputes(status);

DROP TRIGGER IF EXISTS set_payments_updated_at ON payments;
CREATE TRIGGER set_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_trainer_posts_updated_at ON trainer_posts;
CREATE TRIGGER set_trainer_posts_updated_at
BEFORE UPDATE ON trainer_posts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
